"""Build the data bundles used when index.html is opened straight from disk (file://).

Browsers block fetch() for file:// pages, so the app falls back to these bundles:

    data/questions.bundle.js          <- data/*.json          (public, committed to git)
    data/private/private.bundle.js    <- data/private/*.json  (private, git-ignored)

Run it after editing any JSON file:

    python tools/build-bundle.py

It also validates the data: required fields, unique IDs (across both folders) and known levels.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
PRIVATE = DATA / "private"

BUNDLES = [
    # (source folder, output file, global variable)
    (DATA, DATA / "questions.bundle.js", "IPH_BUNDLE"),
    (PRIVATE, PRIVATE / "private.bundle.js", "IPH_PRIVATE_BUNDLE"),
]

REQUIRED = ("id", "subject", "question", "answer")
LEVELS = {"", "Beginner", "Intermediate", "Advanced"}


def read_folder(folder, seen_ids, errors):
    bundle = {}
    for path in sorted(folder.glob("*.json")):
        name = path.relative_to(DATA).as_posix()
        try:
            items = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            errors.append(f"{name}: invalid JSON ({exc})")
            continue
        if not isinstance(items, list):
            errors.append(f"{name}: must contain a JSON array")
            continue

        for n, item in enumerate(items, start=1):
            where = f"{name} item {n}"
            missing = [field for field in REQUIRED if not item.get(field)]
            if missing:
                errors.append(f"{where}: missing {', '.join(missing)}")
            if item.get("level", "") not in LEVELS:
                errors.append(f"{where}: level must be one of {sorted(LEVELS - {''})} or empty")
            qid = item.get("id")
            if qid in seen_ids:
                errors.append(f"{where}: duplicate id {qid!r} (also in {seen_ids[qid]})")
            seen_ids[qid] = where

        bundle[path.stem] = items
    return bundle


def write_bundle(bundle, out, variable):
    payload = json.dumps(bundle, ensure_ascii=False, separators=(",", ":"))
    payload = payload.replace("</", "<\\/")          # never close the <script> tag early
    out.write_text(
        "/* Generated by tools/build-bundle.py. Do not edit by hand. */\n"
        f"window.{variable} = {payload};\n",
        encoding="utf-8",
    )
    total = sum(len(items) for items in bundle.values())
    print(f"Wrote {out.relative_to(ROOT).as_posix()}: {len(bundle)} files, {total} questions")


def main() -> int:
    seen_ids, errors, results = {}, [], []
    for folder, out, variable in BUNDLES:
        bundle = read_folder(folder, seen_ids, errors) if folder.is_dir() else {}
        results.append((bundle, out, variable))

    if errors:
        print("Bundles NOT written. Fix these problems first:")
        for err in errors:
            print("  -", err)
        return 1

    for bundle, out, variable in results:
        if bundle:
            write_bundle(bundle, out, variable)
        elif out.exists():
            out.unlink()                              # folder emptied: remove the old bundle
    return 0


if __name__ == "__main__":
    sys.exit(main())
